services:
  - type: web
    name: profilio-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.bdcifdaqwlehlbjwezap.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false   # donâ€™t hardcode secrets, set them in Render dashboard
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
